### ISSUE TITLE
Autoformat support

### ISSUE THREAD

**Issue by sindresorhus** [xojs/vim-xo#1]
I currently have a [tip about autoformatting](https://github.com/sindresorhus/vim-xo#tip) in the readme, but would be nicer to bundle it in the plugin somehow.

Anyone know how I could do that?

// @gautaz @arthurvr

**Comment by gautaz** [comment]
Perhaps the best way would be to make a PR to [vim-autoformat](https://github.com/Chiel92/vim-autoformat) to add `xo` as a default formatter.
AFAIK [defaults.vim](https://github.com/Chiel92/vim-autoformat/blob/master/plugin/defaults.vim#L159) and the [README.md](https://github.com/Chiel92/vim-autoformat/blob/master/README.md) have to be modified.
As an example, this as been done previously for [standard](https://github.com/feross/standard) in this [commit](https://github.com/Chiel92/vim-autoformat/commit/091321ce4d32a2d124a803ac08bc0ba01cc154ed#diff-04c6e90faac2675aa89e2176d2eec7d8).

Doing the whole autoformatting process directly in `vim-xo` would basically mean implementing again what is done in [vim-autoformat](https://github.com/Chiel92/vim-autoformat) in a simpler manner.
But as `vim-xo` uses [syntastic](https://github.com/vim-syntastic/syntastic) for syntax checking, I guess this is kinda binding the syntax checker to the autoformatter which is not always what vim people want (I use for instance [neomake](https://github.com/neomake/neomake) under [neovim](https://neovim.io/) for syntax checking).

Hope this helps...

**Comment by gautaz** [comment]
I've just read again my previous comment and my last sentence is misleading. Instead of "binding the syntax checker to the auto-formatter", I should have said "binding the plugins in charge of launching both syntax checker and auto-formatter".

**Comment by sindresorhus** [comment]
@gautaz Thanks for the tip. I did a PR on vim-autoformat: https://github.com/Chiel92/vim-autoformat/pull/160

**Comment by gautaz** [comment]
Cool ! You're welcome.

**Comment by titanism** [comment]
We have submitted a PR which now uses `npx` instead of `xo` (since xo global is no longer supported) https://github.com/vim-autoformat/vim-autoformat/pull/377
